name: Build on PR Comment

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'ghtoped setup')
    runs-on: ubuntu-latest
    steps:
      - name: Split version code
        uses: Team-Travel-Bareng/prompt-args@args-workflows
        id: split
        with:
          string: ${{ github.event.comment.body }}
          limit: -1

      - name: Some other action
        run: |
          echo ${{ steps.split.outputs.length }}
          echo ${{ steps.split.outputs.separator }}
          echo ${{ steps.split.outputs.job }}
          echo ${{ steps.split.outputs.environment }}
          echo ${{ steps.split.outputs.config }}
