name: Build on PR Comment

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'ghtoped setup')
    runs-on: ubuntu-latest
    steps:
      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
          string: ${{ github.event.comment.body }}
          separator: " "
          limit: -1

      - name: Some other action
        run: |
          echo ${{ steps.split.outputs._0 }}
          echo ${{ steps.split.outputs._1 }}

