name: Build on PR Comment

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'ghtoped setup')
    runs-on: ubuntu-16.04
    steps:
      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
          string: github.event.comment.body
          limit: -1

      - name: Some other action
        with:
          major: ${{ steps.split.outputs._0 }}
          minor: ${{ steps.split.outputs._1 }}
          patch: ${{ steps.split.outputs._2 }}
          
          #test
