name: Build on PR Comment

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'ghtoped setup')
    runs-on: ubuntu-latest
    steps:
      - name: Split version code
        uses: Team-Travel-Bareng/prompt-args@comment-flags
        id: split
        with:
          comment: ${{ github.event.comment.body }}

      - name: Some other action
        run: |
          echo ${{ fromJSON(steps.split.outputs.result).env }}
          echo ${{ fromJSON(steps.split.outputs.result).tags }}
          echo ${{ fromJSON(steps.split.outputs.result).address }}
          echo ${{ fromJSON(steps.split.outputs.result).playbook }}
          
      - name: list directory
        run: |
          ls -la
          pwd
          
      - name: script
        run: |
          cd
          chmod +x ./script.sh
          ./script.sh
          

