name: Build on PR Comment

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    if: github.event.issue.pull_request && (startsWith(github.event.comment.body, 'setup') || startsWith(github.event.comment.body, 'build'))
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Split version code
        uses: Team-Travel-Bareng/prompt-args@comment-flags
        id: split
        with:
          comment: ${{ github.event.comment.body }}

      - name: Some other action
        run: |
          echo ${{ fromJSON(steps.split.outputs.result).env }}
          echo ${{ fromJSON(steps.split.outputs.result).tags }}
          echo ${{ fromJSON(steps.split.outputs.result).address }}
          echo ${{ fromJSON(steps.split.outputs.result).playbook }}
          
      - name: test if
        id: test-if
        run: |
          build="build"
          setup="setup"
          if [[ "${{ startsWith(github.event.comment.body, 'setup') }}" == 'true' ]]; then
            echo ::set-output name=test-output::$setup
          fi
          if [[ "${{ startsWith(github.event.comment.body, 'build') }}" == 'true' ]]; then
            echo ::set-output name=test-output::$build
          fi
      - name: echo outputs
        run: echo ${{ steps.test-if.outputs.test-output }}
          

